### ISSUE TITLE
Some miscellaneous questions.

### ISSUE THREAD

**Issue by adsmendesdaniel** [analysiscenter/pydens#13]
When I dont define a "body", whats is the structure of the network?
Theres some easy way to save my trained network, so I can use it?

**Comment by akoryagin** [comment]
Hey, @adsmendesdaniel!

Let's start with the structure of the network. In fact, the default network architecture depends on the dimensionality of the problem. For, say, 2-dimensional pde-problem, the network will have a layout of
```
fa Rfa+
```
which stands for a **f**ully connected network with skip-connection (`R` for start of the skip and `+` for the end); while for the 3-dimensional pde-problem, there will be an additional skip-block:
```
fa Rfa+ Rfa+
```
Note also, that whenever the default architecture is used, the width of the network can be regulated by a parameter `layer_size`:
```
dg = Solver(config, layer_size=15) 
```

As for the second part of your question: yes, it can be done as follows:
```
path = './'
dg.model.save(path)
dg_loaded = Solver(config) # the same config that was used for the original model initialization
dg_loaded.model.load(path)
```
Of course, it's not very pretty right now. Expect a better loading procedure soon!

Best,
Alex.
