### ISSUE TITLE
boundry conditions

### ISSUE THREAD

**Issue by mohsenhos** [analysiscenter/pydens#23]
![image](https://user-images.githubusercontent.com/49274685/78996341-a217dc80-7b59-11ea-8334-1ab751bf2d30.png)
 Hi 
how can i add this boundry condition with limited domain in this code
thanks for your attention

**Comment by akoryagin** [comment]
Hey, @mohsenhos!

Boundary condition of Neumann type is to be implemented in upcoming months!

Best,
Alexander
