### ISSUE TITLE
How can I change the interval of x 

### ISSUE THREAD

**Issue by katayooneshkofti** [analysiscenter/pydens#24]
Hello Everyone
I want to change the interval of x. Instead of using the default one [0,1], I want to have [1, 1.5] so I can define my boundary conditions in these two points? 
How could I modify the code?

**Comment by RahulSundar** [comment]
Hi @katayooneshkofti 
Instead of modifying the code, you could simply scale and shift your equations such that [1, 1.5] ---> [0,1]. You can then go about using the code as it is.

**Comment by RahulSundar** [comment]
You could as well add and specify the keyword "domain" while specifying the config for the pde you are solving. For example, in the below snippet I have specified a very general domain [a, b]. 
```
pde = {'n_dims': 2,
       'form': lambda u, x, y: D(D(u, x), x) + D(D(u, y), y) - 5 * sin(np.pi * (x + y)),
       'boundary_condition': 1
       'domain': **[a,b]**              }

body = {'layout': 'fa fa fa f',
        'units': [15, 25, 15, 1],
        'activation': [tf.nn.tanh, tf.nn.tanh, tf.nn.tanh]}

config = {'body': body,
          'pde': pde
           }
```

**Comment by katayooneshkofti** [comment]
> You could as well add and specify the keyword "domain" while specifying the config for the pde you are solving. For example, in the below snippet I have specified a very general domain [a, b].
> 
> ```
> pde = {'n_dims': 2,
>        'form': lambda u, x, y: D(D(u, x), x) + D(D(u, y), y) - 5 * sin(np.pi * (x + y)),
>        'boundary_condition': 1
>        'domain': **[a,b]**              }
> 
> body = {'layout': 'fa fa fa f',
>         'units': [15, 25, 15, 1],
>         'activation': [tf.nn.tanh, tf.nn.tanh, tf.nn.tanh]}
> 
> config = {'body': body,
>           'pde': pde
>            }
> ```

Thank you Rahul for your prompt response. Actually, I didn't pay attention to that keyword. I read the paper once again and voila I found that. Thank you for your consideration.
