### ISSUE TITLE
How to install easily with PIP command?

### ISSUE THREAD

**Issue by hossein-amini67** [analysiscenter/pydens#27]
Dear Guys
I am extremely interested in working with your product but I have a problem installing the packages. I installed using different ways but I faced "No module named 'pydens.batchflow'" and I do not have any idea to solve it. I will appreciate it if could do a favor of installing. 

Thanks in advanced

**Comment by RahulSundar** [comment]
Dear Hossein
You could first create a python3 virtual environment for pydens using virtualenv or other means. Then, you could activate your environment and install all the dependencies using:
`pip3 install pydens`
This mostly works on any system as per my experience. Just ensure that in the installation logs, you see that the dependencies are all installed and that tensorflow version is 1.14. 
However, if you are comfortable working with the development version you could follow the instructions as given in the readme file within the virtual environment. The  virtual environment would ensure that you don't harm your other python packages already installed.
Thanks
Rahul
