### ISSUE TITLE
"No module named 'pydens.batchflow' "

### ISSUE THREAD

**Issue by adsmendesdaniel** [analysiscenter/pydens#8]
I'm using Spyder3 to run this code:

`
import pydens as pde
from pydens import D
import numpy as np
import tensorflow as tf

pde.add_tokens()

pde = {'n_dims': 2,
       'form': lambda u, x, y: D(D(u, x), x) + D(D(u, y), y) - 5 * pde.sin(np.pi * (x + y)),
       'boundary_condition': 1}

body = {'layout': 'fa fa fa f', #estrutura da rede neural (layers)
        'units': [15, 25, 15, 1], #neurônios por camada
        'activation': [tf.nn.tanh, tf.nn.tanh, tf.nn.tanh]} #ativação advinda do TFlow
        
config = {'body': body,
          'pde': pde}

us = pde.NumpySampler('uniform', dim=2) 

dg = pde.Solver(config)
dg.fit(batch_size=100, sampler=us, n_iters=1500) 
`
...and I'm getting this error:

`File "C:\Users\my_user\Anaconda3\lib\site-packages\pydens\letters.py", line 20, in <module>
    from .batchflow.models.tf.layers import conv_block

ModuleNotFoundError: No module named 'pydens.batchflow'`

My tersorflow are actualized and I got PyDEns and Batchflow with pip on conda terminal.

**Comment by adsmendesdaniel** [comment]
> I'm using Spyder3 to run this code:
> 
> `
> import pydens as pde
> from pydens import D
> import numpy as np
> import tensorflow as tf
> 
> pde.add_tokens()
> 
> pde = {'n_dims': 2,
> 'form': lambda u, x, y: D(D(u, x), x) + D(D(u, y), y) - 5 * pde.sin(np.pi * (x + y)),
> 'boundary_condition': 1}
> 
> body = {'layout': 'fa fa fa f', #estrutura da rede neural (layers)
> 'units': [15, 25, 15, 1], #neurônios por camada
> 'activation': [tf.nn.tanh, tf.nn.tanh, tf.nn.tanh]} #ativação advinda do TFlow
> 
> config = {'body': body,
> 'pde': pde}
> 
> us = pde.NumpySampler('uniform', dim=2)
> 
> dg = pde.Solver(config)
> dg.fit(batch_size=100, sampler=us, n_iters=1500)
> `
> ...and I'm getting this error:
> 
> `File "C:\Users\my_user\Anaconda3\lib\site-packages\pydens\letters.py", line 20, in
> from .batchflow.models.tf.layers import conv_block
> 
> ModuleNotFoundError: No module named 'pydens.batchflow'`
> 
> My tersorflow are actualized and I got PyDEns and Batchflow with pip on conda terminal.

Do Tensorflow have to be version 1.14??

**Comment by akoryagin** [comment]
Hey, @adsmendesdaniel!

First of all, thanks for the interest!

It looks like installation from PyPI doesn't work: clearly, we've forgotten to upload `batchflow`-submodule on the repository. We'll fix this as soon as possible! As of now, you can install `pydens` using
```
pip3 install git+https://github.com/analysiscenter/pydens.git
``` 
This command will automatically include the needed `batchflow`-submodule.

As to your second question: `pydens` should work just fine with `tensorflow 1.8` and higher.

Best,
Alex

**Comment by adsmendesdaniel** [comment]
> Hey, @adsmendesdaniel!
> 
> First of all, thanks for the interest!
> 
> It looks like installation from PyPI doesn't work: clearly, we've forgotten to upload `batchflow`-submodule on the repository. We'll fix this as soon as possible! As of now, you can install `pydens` using
> 
> ```
> pip3 install git+https://github.com/analysiscenter/pydens.git
> ```
> 
> This command will automatically include the needed `batchflow`-submodule.
> 
> As to your second question: `pydens` should work just fine with `tensorflow 1.8` and higher.
> 
> Best,
> Alex

Sorry, I installed pydens with pip and anaconda git, but I'm still getting the problem...

**Comment by akoryagin** [comment]
That looks strange. Did you try to uninstall the previous version of `pydens` before reinstalling it using `pip` + `git`?

If uninstalling doesn't help, I'd suggest you to use
```
git clone --recursive https://github.com/analysiscenter/pydens.git
```
for the installation of `pydens` into a specific folder.

Best,
Alex

**Comment by adsmendesdaniel** [comment]
It worked!! Probably it wasn't running because I didn't uninstall the previous version. 
Thank you.

**Comment by hossein-amini67** [comment]
Well, I have a problem even with the initial things like installing and then the current error that has been posted on this page. I do not know how to install using "git" since the windows does not accept installing though that command. Of course,
![photo_2020-10-09_16-18-57](https://user-images.githubusercontent.com/50735709/95594413-2b499680-0a4b-11eb-8861-c7667821464b.jpg)
 I have added in my variable environment the new paths but still, I am suffering from that.

**Comment by hossein-amini67** [comment]
> Hello,
> 
> you should probably try to install `git` by using [this](https://git-scm.com/download/win)
> 
> Sergey

Dear ,
thanks for your prompt reply. I did it at the time but I faced the issue of this page "No module named 'pydens.batchflow'" and I followed the steps of the page but nothing changed and happened.

**Comment by SergeyTsimfer** [comment]
Try to completely uninstall everything and run `git clone --recursive https://github.com/analysiscenter/pydens.git`, as it seems that `batchflow` submodule was not correctly pulled
